### PR TITLE
Added integration tests and n+1 fixes

### PR DESCRIPTION
**Pull request by jfoyarzo**
For this milestone of the project, the following changes were introduced:
- Solved the N+1 problem when fetching all posts and their comments for a user
- Used Capybara to write integration tests for each view present in the project.

- Screenshots before n+1 fix:
screenshot2-before
screenshot-before

- Screenshots after the fixes:
screenshot2-after
screenshot-after

### CODE REVIEW

**Review by ridwanediallo — APPROVED** [review]
# STATUS: APPROVED 🟢
## Hi @jfoyarzo, 
Congratulations!GIF

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All tests are passing. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MattGomb** [comment]
We did not see, that both repos need to be updated, not just one, so I am resubmitting this so I can pass my own review

**Review by omar-muhamad — COMMENTED** [review]
# Approved ✔
### Hi @MattGomb,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by omar-muhamad** [comment]
Hi @MattGomb,
I approved it because This is your repo, The other (your collaborator @jfoyarzo ) submission is supposed to be invalidated not approved.

**Pull request merged**
